// <auto-generated />
using System;
using CardPlay.Repository.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardPlay.Repository.Migrations
{
    [DbContext(typeof(CardPlayDbContext))]
    partial class CardPlayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CardPlay.Domain.Entidades.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAmigavel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cartoes", (string)null);
                });

            modelBuilder.Entity("CardPlay.Domain.Entidades.MovimentacaoCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("MovimentacoesCartao", (string)null);
                });

            modelBuilder.Entity("CardPlay.Domain.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCurta")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a7e-0c4a-4b1d-9e2f-1a2b3c4d5e6f"),
                            DescricaoCurta = "Um espresso cremoso para começar bem o dia.",
                            Disponivel = true,
                            Icone = "☕",
                            Nome = "Café especial",
                            Preco = 8.50m
                        },
                        new
                        {
                            Id = new Guid("7a2d3b8f-1d5b-4c2e-8f3a-2b3c4d5e6f70"),
                            DescricaoCurta = "História curta com arte colorida para ler no intervalo.",
                            Disponivel = true,
                            Icone = "📘",
                            Nome = "Livro ilustrado",
                            Preco = 32.90m
                        },
                        new
                        {
                            Id = new Guid("8b3e4c9a-2e6c-4d3f-9a4b-3c4d5e6f7081"),
                            DescricaoCurta = "Áudio leve para estudar ou ouvir um podcast.",
                            Disponivel = true,
                            Icone = "🎧",
                            Nome = "Fone compacto",
                            Preco = 79.00m
                        },
                        new
                        {
                            Id = new Guid("9c4f5d0b-3f7d-4e4a-ab5c-4d5e6f708192"),
                            DescricaoCurta = "Um sticker brilhante para personalizar seu caderno.",
                            Disponivel = true,
                            Icone = "🌟",
                            Nome = "Adesivo CardPlay",
                            Preco = 4.00m
                        },
                        new
                        {
                            Id = new Guid("ad506e1c-408e-4f5b-bc6d-5e6f708192a3"),
                            DescricaoCurta = "Combo doce e salgado para recarregar a energia.",
                            Disponivel = true,
                            Icone = "🥪",
                            Nome = "Lanche da tarde",
                            Preco = 18.75m
                        },
                        new
                        {
                            Id = new Guid("be617f2d-519f-406c-cd7e-6f708192a3b4"),
                            DescricaoCurta = "Algodão macio com estampa do cartão virtual.",
                            Disponivel = true,
                            Icone = "👕",
                            Nome = "Camiseta lúdica",
                            Preco = 59.90m
                        });
                });

            modelBuilder.Entity("CardPlay.Domain.Entidades.MovimentacaoCartao", b =>
                {
                    b.HasOne("CardPlay.Domain.Entidades.Cartao", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardPlay.Domain.Entidades.Cartao", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
